version: '3.4'

services:
  be-home:
    image: idealful/example:1.0.0
    container_name: be-home
    build:
      context: ./be-home
      dockerfile: ./Dockerfile-dev
    ports:
      - '8001:8001'
    environment:
      - DB_HOST=host.docker.internal
  be-auth:
    image: idealful/example:2.0.0
    container_name: be-auth
    build:
      context: ./be-auth
      dockerfile: ./Dockerfile-dev
    ports:
      - '8002:8002'
  fe:
    image: idealful/example:4.0.0
    container_name: fe
    build:
      context: ./fe
      dockerfile: ./Dockerfile-dev
    ports:
      - '80:80'
