version: '3.9'

services:
  be-home:
    image: idealful/sc-be-home
    container_name: be-home
    build:
      context: ./be-home
      dockerfile: ./Dockerfile-dev
    ports:
      - '8001:8001'
    environment:
      - DB_HOST=host.docker.internal
  be-auth:
    image: idealful/sc-be-auth
    container_name: be-auth
    build:
      context: ./be-auth
      dockerfile: ./Dockerfile-dev
    ports:
      - '8002:8002'
  be-member:
    image: idealful/sc-be-member
    container_name: be-member
    build:
      context: ./be-member
      dockerfile: ./Dockerfile-dev
    ports:
      - '8003:8003'
    environment:
      - DB_HOST=host.docker.internal
