version: '3.4'

services:
  be-home:
    image: 817757596025.dkr.ecr.ap-northeast-2.amazonaws.com/schedulechecker_be_home:latest
    container_name: be-home
    build:
      context: ./be-home
      dockerfile: ./Dockerfile
    ports:
      - '8001:8001'
    environment:
      - DB_HOST=10.0.144.10
  be-auth:
    image: 817757596025.dkr.ecr.ap-northeast-2.amazonaws.com/schedulechecker_be_auth:latest
    container_name: be-auth
    build:
      context: ./be-auth
      dockerfile: ./Dockerfile
    ports:
      - '8002:8002'
  fe:
    image: 817757596025.dkr.ecr.ap-northeast-2.amazonaws.com/schedulechecker_fe:latest
    container_name: fe
    build:
      context: ./fe
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
    environment:
      - VITE_APP_SERVER=
