name: Schedule Checker CI
on: push
jobs:
  sc-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Change Directory to fe
        run: cd fe
      - name: Import actions from github
        uses: actions/checkout@v3
      - name: Do npm install by actions
        run: npm ci
